{{- if .Values.clusterRole.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.clusterRoleName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
      - create
      - patch
      - update
  - apiGroups:
    - apps
    resources:
      - daemonsets
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - patch
      - watch
  {{ if .Values.clusterRole.extraRules }}
  {{- toYaml .Values.clusterRole.extraRules }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.clusterRoleName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "chart.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "chart.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}

